### PR TITLE
Feature improve UI

### PR DESCRIPTION
**Pull request by gantlavamshikrishnareddy**
updated to spacebar event.

### CODE REVIEW

**Review by gantlavamshikrishnareddy — COMMENTED** [review]
This spacebar event spellchecking is user friendly then previous one.

**Review by naveenreddy0 — COMMENTED** [review]
Why did you change to keypress event

**Review by gantlavamshikrishnareddy — COMMENTED** [review]
THIS WAY OF SPELLCHECK IS BETTER THAN PREVIOUS ONE,BUT WHY YOU CHANGED FROM ONCLICK TO SPACEBAR.

**Review by gantlavamshikrishnareddy — COMMENTED** [review]
THIS WAY OF SPELLCHECK IS BETTER THAN PREVIOUS ONE,BUT WHY YOU CHANGED FROM ONCLICK TO SPACEBAR.

**Comment by gantlavamshikrishnareddy** [comment]
> Why did you change to keypress event

The previous change couldn't flag what is wrong and what is correct.

**Pull request merged**
